### ISSUE TITLE
Issue with multiple namespace blocks.

### ISSUE THREAD

**Issue by kwhat** [phpDocumentor/Reflection#107]
Hi,

I was trying to run just a stand-alone example for this project on 5.6 and I am encountering the following error:

```
PHP Fatal error:  Uncaught exception 'PhpParser\Error' with message 'No code may exist outside of namespace {} on line 268' in /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:427
Stack trace:
#0 /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php(797): PhpParser\ParserAbstract->handleNamespaces(Array)
#1 /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(247): PhpParser\Parser\Php7->reduceRule1()
#2 /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(59): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#3 /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(30): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php7), '<?php\n\n in /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 427

Fatal error: Uncaught exception 'PhpParser\Error' with message 'No code may exist outside of namespace {} on line 268' in /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 427

PhpParser\Error: No code may exist outside of namespace {} on line 268 in /Users/alexander.barker/projects/Reflection/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 427

Call Stack:
    0.0002     229936   1. {main}() /Users/alexander.barker/projects/Reflection/example.php:0
    0.0370    7519464   2. phpDocumentor\Reflection\Php\ProjectFactory->create() /Users/alexander.barker/projects/Reflection/example.php:29
    0.0384    7571560   3. phpDocumentor\Reflection\Php\Factory\AbstractFactory->create() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:79
    0.0384    7571648   4. phpDocumentor\Reflection\Php\Factory\File->doCreate() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/Factory/AbstractFactory.php:28
    0.0387    7577864   5. phpDocumentor\Reflection\Php\Factory\File->phpDocumentor\Reflection\Php\Factory\{closure}() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/Factory/File.php:92
    0.0387    7578088   6. phpDocumentor\Reflection\Php\Factory\File->createFile() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/Factory/File.php:60
    0.0389    7584584   7. phpDocumentor\Reflection\Php\NodesFactory->create() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/Factory/File.php:103
    0.0389    7584760   8. PhpParser\Parser\Multiple->parse() /Users/alexander.barker/projects/Reflection/src/phpDocumentor/Reflection/Php/NodesFactory.php:79
```

It appears that the namespace node is getting set as a Nop and thus throwing an error for more than one because of [!$stmt instanceof Node\Stmt\HaltCompiler](https://github.com/nikic/PHP-Parser/blob/2.x/lib/PhpParser/ParserAbstract.php#L426).  I am not familiar enough with this project or php-parser to further identify why this is the case or what the behavior should be, however,  I don't suspect that this is desired behavior on the example.test.php file.

**Comment by jaapio** [comment]
We do not support this library on php 5.6. Please upgrade to php 7.1 or higher.
